export const ADD_REVIEW_AND_RATING_REQUEST = "ADD_REVIEW_AND_RATING_REQUEST"
export const ADD_REVIEW_AND_RATING_SUCCESS = "ADD_REVIEW_AND_RATING_SUCCESS"
export const ADD_REVIEW_AND_RATING_FAILURE = "ADD_REVIEW_AND_RATING_FAILURE"

export const EDIT_REVIEW_AND_RATING_REQUEST = "EDIT_REVIEW_AND_RATING_REQUEST"
export const EDIT_REVIEW_AND_RATING_SUCCESS = "EDIT_REVIEW_AND_RATING_SUCCESS"
export const EDIT_REVIEW_AND_RATING_FAILURE = "EDIT_REVIEW_AND_RATING_FAILURE"

export const DELETE_REVIEW_AND_RATING_REQUEST = "DELETE_REVIEW_AND_RATING_REQUEST"
export const DELETE_REVIEW_AND_RATING_SUCCESS = "DELETE_REVIEW_AND_RATING_SUCCESS"
export const DELETE_REVIEW_AND_RATING_FAILURE = "DELETE_REVIEW_AND_RATING_FAILURE"