export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_FAILURE = "PRODUCT_FAILURE"

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST"
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS"
export const SINGLE_PRODUCT_FAILURE = "SINGLE_PRODUCT_FAILURE"
