export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE"

export const FETCH_MY_ORDER_REQUEST = "FETCH_MY_ORDER_REQUEST"
export const FETCH_MY_ORDER_SUCCESS = "FETCH_MY_ORDER_SUCCESS"
export const FETCH_MY_ORDER_FAILURE = "FETCH_MY_ORDER_FAILURE"