export const Types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE_400: 'LOGIN_FAILURE_400',
    LOGIN_FAILURE_500: 'LOGIN_FAILURE_500',
    RESET_FIELD_ERROR_MSG: 'RESET_FIELD_ERROR_MSG',
  }