export const footerData = [
    {
        header:'company',
        data:[
            {
                name:'about',
                path:'/about'
            },
            {
                name:'blog',
                path:'/blog'
            },
            {
                name:'career',
                path:'/career'
            },
            {
                name:'contact us',
                path:'/contact-us'
            },
            {
                name:'partners',
                path:'/partners'
            },

        ]
    },{
        header:'Solutions',
        data:[
            {
                name:'Marketing',
                path:'/Marketing'
            },
            {
                name:'Analytics',
                path:'/Analytics'
            },
            {
                name:'Commerce',
                path:'/Commerce'
            },
            {
                name:'Insights',
                path:'/Insights'
            },
            {
                name:'Support',
                path:'/Support'
            },

        ]
    },{
        header:'Documentation',
        data:[
            {
                name:'guides',
                path:'/about'
            },
            {
                name:'API Status',
                path:'/api-status'
            }
        ]
    },{
        header:'Legal',
        data:[
            {
                name:'claim',
                path:'/claim'
            },
            {
                name:'privacy',
                path:'/privacy'
            },
            {
                name:'terms',
                path:'/terms'
            }

        ]
    },
]