export const USER_ADDRESS_REQUEST = 'USER_ADDRESS_REQUEST'
export const USER_ADDRESS_SUCCESS = 'USER_ADDRESS_SUCCESS'
export const USER_ADDRESS_FAILURE = 'USER_ADDRESS_FAILURE'

export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST'
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE'

export const EDIT_ADDRESS_REQUEST = 'EDIT_ADDRESS_REQUEST'
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS'
export const EDIT_ADDRESS_FAILURE = 'EDIT_ADDRESS_FAILURE'

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE'
